spring:
  bus:
    group: election
    name: ${spring.application.name}
    index: 0
logging:
  level:
    com.netflix.discovery: 'OFF'
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 10
